### ISSUE TITLE
Add CMake guidelines

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/best-practices#5]
As a start, such written *rules* and procedures would prevent from introducing unwanted naming patterns and help to delimit the current ones. Let's expand on d5438ee:

- *SCREAMING\_SNAKE\_CASE* for the project name and configuration variables: `TEO_MAIN`, `TEO_MAIN_LINK_DIRS`.
- *kebab-case* for installed YARP context directories as set by `yarp_configure_external_installation()`: `teo-main`, `asibot-openrave-models`.
- Use the `ROBOTICSLAB_` (or `roboticslab-`) prefix whenever the uniqueness of the chosen name for the project could be easily compromised (keep in mind you'll want to invoke `find_package()`): `ROBOTICSLAB_YARP_DEVICES`, `ROBOTICSLAB_KINEMATICS_DYNAMICS_INCLUDE_DIRS`, `roboticslab-vision`.

**Comment by PeterBowman** [comment]
OT do we really need a `master` branch here and at [installation-guides](https://github.com/roboticslab-uc3m/installation-guides)? (by the way, such considerations actually belong to `best-practices` should we enforce the GitFlow workflow everywhere)

**Comment by jgvictores** [comment]
> OT do we really need a master branch here and at installation-guides? (by the way, such considerations actually belong to best-practices should we want to enforce the GitFlow workflow everywhere)

Moved to https://github.com/roboticslab-uc3m/best-practices/issues/6

 > As a start, such written rules and procedures would prevent from introducing unwanted naming patterns and help to delimit the current ones. Let's expand on d5438ee:

    SCREAMING_SNAKE_CASE for the project name and configuration variables: TEO_MAIN, TEO_MAIN_LINK_DIRS.
    kebab-case for installed YARP context directories as set by yarp_configure_external_installation(): teo-main, asibot-openrave-models.
    Use the ROBOTICSLAB_ (or roboticslab-) prefix whenever the uniqueness of the chosen name for the project could be easily compromised (keep in mind you'll want to invoke find_package()): ROBOTICSLAB_YARP_DEVICES, ROBOTICSLAB_KINEMATICS_DYNAMICS_INCLUDE_DIRS, roboticslab-vision.

I've found yet another convention: https://github.com/roboticslab-uc3m/installation-guides ...put an issue: https://github.com/roboticslab-uc3m/installation-guides/issues/7

**Comment by PeterBowman** [comment]
`SCREAMING_SNAKE_CASE` convention has been proposed to cover `*.cmake` configuration files like `PROJECT_NAMEConfig.cmake.in`, `PROJECT_NAMEDescribe.cmake`, etc. See 62c1382.

**Comment by jgvictores** [comment]
This currently exists at:
- https://github.com/roboticslab-uc3m/best-practices/blob/7ccd3d4b61d69e72a8feaa3e195d3a69308b013c/en/best-practices.md#programming-in-cmake
- https://github.com/roboticslab-uc3m/best-practices/blob/7ccd3d4b61d69e72a8feaa3e195d3a69308b013c/es/best-practices.md#programaci%C3%B3n-cmake
