### ISSUE TITLE
Should Gitflow be required on gitbook-like repos?

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/best-practices#6]
Should Gitflow be required on gitbook-like repos?

I'm happy with it, but am extracting the question from OT https://github.com/roboticslab-uc3m/best-practices/issues/5#issuecomment-285355654

**Comment by jgvictores** [comment]
Commenting with @PeterBowman , we are going to remove `develop` from the following gitbook-like repos:
- https://github.com/roboticslab-uc3m/best-practices
- https://github.com/roboticslab-uc3m/installation-guides (:skull_and_crossbones:`develop`:skull_and_crossbones: UPDATE REPOS!!!) 
- https://github.com/roboticslab-uc3m/teo-software-manual
- https://github.com/roboticslab-uc3m/teo-hardware-manual
- https://github.com/roboticslab-uc3m/QA

**Comment by rsantos88** [comment]
Done it!

**Comment by jgvictores** [comment]
Updated several `CONTRIBUTING.md`.

**Comment by jgvictores** [comment]
Ended documenting at e20b81b809aae5fa57f0d1d3ba75a22fcbd6f4d7 and b2887d511a23895e021649cf0416945932fc41c6.

**Comment by jgvictores** [comment]
@rsantos88 Thanks for all the changes!!!
